language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 7.1

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mysql -e "create database IF NOT EXISTS shelf_dev;" -uroot
  - vendor/bin/phinx migrate
  - vendor/bin/phinx seed:run

install:
  - composer install --ignore-platform-reqs --no-interaction

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - composer code:check
  - composer test:all

after_script:
  - travis_retry composer upload-coverage

cache:
  directories:
  - $HOME/.composer/cache
  - vendor
